language: python
sudo: required
dist: trusty

python:
- 2.6
- 2.7

install:
- sudo apt-get update
- sudo apt-get -y install python-pyside
- pip install coveralls

script:
- python run_tests.py
- pip install git+git://github.com/pyblish/pyblish-lite.git

after_success:
- coveralls
