language: python
python:
  - 3.4
addons:
  apt:
    packages:
    - qt4-qmake
    - libqt4-dev
install:
  - pip install --upgrade pip
  - pip install PySide --no-index --find-links https://parkin.github.io/python-wheelhouse/;
  - python ~/virtualenv/python${TRAVIS_PYTHON_VERSION}/bin/pyside_postinstall.py -install

# command to run tests
script:
- python run_tests.py
- pip install git+git://github.com/pyblish/pyblish-lite.git

after_success:
- coveralls